/**
 * THIS FILE IS AUTO-GENERATED FROM CONTENTFUL
 * Do not edit this file directly
 * Generated on: 2025-08-07T15:55:06.366Z
 */

export interface EntryFields {
  [key: string]: any;
}

export interface EntrySkeletonType<T extends EntryFields = EntryFields> {
  sys: {
    id: string;
    createdAt: string;
    updatedAt: string;
    contentTypeId: string;
  };
  fields: T;
}

export interface IimplementationvariationsFields {
  title?: string | undefined;
  samenvatting?: string | undefined;
  geschatteJaarlijkseKosten?: string | undefined;
  geschatteKostenPerKmPp?: string | undefined;
  geschatteKostenPerRit?: string | undefined;
  // Fields removed in Contentful: verantwoordelijkheid, contractvormen, voordelen, nadelen
  mobiliteitsdienstVariant?: { sys: { id: string } };
  investering?: string | undefined;
  realisatieplan?: string | undefined;
  realisatieplanLeveranciers?: string | undefined;
  realisatieplanContractvormen?: string | undefined;
  realisatieplanKrachtenveld?: string | undefined;
  realisatieplanVoorsEnTegens?: string | undefined;
  realisatieplanAandachtspunten?: string | undefined;
  realisatieplanChecklist?: string | undefined;
  governanceModels?: { sys: { id: string } }[];
  governanceModelsMits?: { sys: { id: string } }[];
  governanceModelsNietgeschikt?: { sys: { id: string } }[];
  geenRechtsvorm?: string | undefined;
  vereniging?: string | undefined;
  stichting?: string | undefined;
  ondernemersBiz?: string | undefined;
  vastgoedBiz?: string | undefined;
  gemengdeBiz?: string | undefined;
  cooperatieUa?: string | undefined;
  bv?: string | undefined;
  ondernemersfonds?: string | undefined;
}

export interface Iimplementationvariations extends EntrySkeletonType<IimplementationvariationsFields> {
  contentTypeId: 'implementationvariations';
}

export interface ImobilityServiceFields {
  title?: string | undefined;
  typeVervoer?: string[];
  ophalen?: string[];
  minimaleInvestering?: string | undefined;
  minimumAantalPersonen?: string | undefined;
  afstand?: string | undefined;
  samenvattingLang?: string | undefined;
  paspoort?: string | undefined;
  description?: string | undefined;
  uitvoering?: string | undefined;
  uitdagingenEnAanleidingen?: string | undefined;
  collectiefVsIndiviueel?: string | undefined;
  casebeschrijving?: string | undefined;
  parkeer_bereikbaarheidsproblemen?: number | undefined;
  parkeerBereikbaarheidsproblemenToelichting?: string | undefined;
  bereikbaarheidsproblemen?: number | undefined;
  bereikbaarheidsproblemenToelichting?: string | undefined;
  personeelszorg_en_behoud?: number | undefined;
  personeelszorgEnBehoudToelichting?: string | undefined;
  gezondheid?: number | undefined;
  gezondheidToelichting?: string | undefined;
  imago?: number | undefined;
  imagoToelichting?: string | undefined;
  milieuverordening?: number | undefined;
  milieuverordeningToelichting?: string | undefined;
}

export interface ImobilityService extends EntrySkeletonType<ImobilityServiceFields> {
  contentTypeId: 'mobilityService';
}

export interface IgovernanceModelFields {
  title?: string | undefined;
  type?: string | undefined;
  samenvatting?: string | undefined;
  description?: string | undefined;
  aansprakelijkheid?: string | undefined;
  // Removed fields kept out intentionally
  benodigdhedenOprichting?: string | undefined;
  links?: string | undefined;
  doorlooptijdLang?: string | undefined;
  implementatie?: string | undefined;
  voorbeeldContracten?: { sys: { id: string } }[];
}

export interface IgovernanceModel extends EntrySkeletonType<IgovernanceModelFields> {
  contentTypeId: 'governanceModel';
}

export interface IbusinessParkReasonFields {
  title: string;
  samenvatting: string;
  description?: string | undefined;
  order: number;
  identifier: string;
}

export interface IbusinessParkReason extends EntrySkeletonType<IbusinessParkReasonFields> {
  contentTypeId: 'businessParkReason';
}

export interface IwebsiteCollectiefVervoerFields {
  inleiding?: string | undefined;
  watIsCollectiefVervoer?: string | undefined;
  processchema?: { sys: { id: string } };
  aanleidingenVoorCollectieveVervoersoplossingen?: string | undefined;
  overzichtCollectieveVervoersoplossingen?: string | undefined;
  bestuurlijkeRechtsvormen?: string | undefined;
  coverSubsidie?: string | undefined;
  bestPractices?: string | undefined;
}

export interface IwebsiteCollectiefVervoer extends EntrySkeletonType<IwebsiteCollectiefVervoerFields> {
  contentTypeId: 'websiteCollectiefVervoer';
}

export interface IquestionFields {
  title?: string | undefined;
  questionText?: string | undefined;
  shortQuestion?: string | undefined;
  order?: number | undefined;
  questionType?: string | undefined;
  minValue?: number | undefined;
  maxValue?: number | undefined;
  identifier: string;
}

export interface Iquestion extends EntrySkeletonType<IquestionFields> {
  contentTypeId: 'question';
}

