// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface IBusinessParkReasonFields {
  /** Title */
  title: string;

  /** Samenvatting */
  samenvatting: string;

  /** description */
  description?: string | undefined;

  /** Order */
  order: number;

  /** identifier */
  identifier: string;
}

/** Dit zijn de aanleidingen voor bedrijventerreinen om op zoek te zijn naar oplossingen. */

export interface IBusinessParkReason extends Entry<IBusinessParkReasonFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "businessParkReason";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IGovernanceModelFields {
  /** Title */
  title?: string | undefined;

  /** Type */
  type?: string | undefined;

  /** Samenvatting */
  samenvatting?: string | undefined;

  /** Description */
  description?: string | undefined;

  /** Aansprakelijkheid */
  aansprakelijkheid?: string | undefined;

  /** Voordelen */
  voordelen?: string | undefined;

  /** Nadelen */
  nadelen?: string | undefined;

  /** Benodigdheden oprichting */
  benodigdhedenOprichting?: string | undefined;

  /** links */
  links?: string | undefined;

  /** doorlooptijd lang */
  doorlooptijdLang?: string | undefined;

  /** Wel geschikt voor */
  welGeschiktVoor?: IMobilityService[] | undefined;

  /** Niet geschikt voor */
  nietGeschiktVoor?: IMobilityService[] | undefined;

  /** implementatie */
  implementatie?: string | undefined;

  /** voorbeeld contracten */
  voorbeeldContracten?: Asset[] | undefined;
}

/** Vul hier het governance model in */

export interface IGovernanceModel extends Entry<IGovernanceModelFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "governanceModel";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IImplementationvariationsFields {
  /** title */
  title?: string | undefined;

  /** samenvatting */
  samenvatting?: string | undefined;

  /** Mobiliteitsdienst variant */
  mobiliteitsdienstVariant?: IMobilityService | undefined;

  /** investering */
  investering?: string | undefined;

  /** realisatieplan */
  realisatieplan?: string | undefined;

  /** realisatieplanLeveranciers */
  realisatieplanLeveranciers?: string | undefined;

  /** realisatieplanContractvormen */
  realisatieplanContractvormen?: string | undefined;

  /** realisatieplanKrachtenveld */
  realisatieplanKrachtenveld?: string | undefined;

  /** realisatieplanVoorsEnTegens */
  realisatieplanVoorsEnTegens?: string | undefined;

  /** realisatieplanAandachtspunten */
  realisatieplanAandachtspunten?: string | undefined;

  /** realisatieplanChecklist */
  realisatieplanChecklist?: string | undefined;

  /** GovernanceModels */
  governanceModels?: IGovernanceModel[] | undefined;

  /** GovernanceModelsMits */
  governanceModelsMits?: IGovernanceModel[] | undefined;

  /** governanceModelsNietgeschikt */
  governanceModelsNietgeschikt?: IGovernanceModel[] | undefined;

  /** Geen rechtsvorm */
  geenRechtsvorm?: string | undefined;

  /** Vereniging */
  vereniging?: string | undefined;

  /** Stichting */
  stichting?: string | undefined;

  /** Ondernemers BIZ */
  ondernemersBiz?: string | undefined;

  /** Vastgoed BIZ */
  vastgoedBiz?: string | undefined;

  /** Gemengde BIZ */
  gemengdeBiz?: string | undefined;

  /** Cooperatie UA */
  cooperatieUa?: string | undefined;

  /** BV */
  bv?: string | undefined;

  /** Ondernemersfonds */
  ondernemersfonds?: string | undefined;
}

export interface IImplementationvariations
  extends Entry<IImplementationvariationsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "implementationvariations";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMobilityServiceFields {
  /** Title */
  title?: string | undefined;

  /** Type vervoer */
  typeVervoer?:
    | ("Woon- werkverkeer" | "Zakelijk verkeer" | "Bezoekers verkeer")[]
    | undefined;

  /** Samenvatting lang */
  samenvattingLang?: string | undefined;

  /** paspoort */
  paspoort?: string | undefined;

  /** Description */
  description?: string | undefined;

  /** Uitvoering */
  uitvoering?: string | undefined;

  /** input businesscase */
  inputBusinesscase?: string | undefined;

  /** implementatievarianten */
  implementatievarianten?:
    | (
        | "Zelf aanschaffen"
        | "Inkopen"
        | "Aansluiten bij het bestaande publiek vervoersysteem"
        | "Extra vervoer toevoegen aan het vervoerssysteem"
        | "Een lid koopt in"
        | "Aanbevolen serviceprovider"
      )[]
    | undefined;

  /** Uitvoeringsmogelijkheden */
  uitvoeringsmogelijkheden?: string | undefined;

  /** collectief-vs-indiviueel */
  collectiefVsIndiviueel?: string | undefined;

  /** investering */
  investering?: string | undefined;

  /** implementatie */
  implementatie?: string | undefined;

  /** minimumInvestment */
  minimumInvestment?: number | undefined;

  /** Parkeer- en bereikbaarheidsproblemen */
  parkeer_bereikbaarheidsproblemen?: number | undefined;

  /** parkeer_bereikbaarheidsproblemen_toelichting */
  parkeerBereikbaarheidsproblemenToelichting?: string | undefined;

  /** Bereikbaarheidsproblemen */
  bereikbaarheidsproblemen?: number | undefined;

  /** bereikbaarheidsproblemen_toelichting */
  bereikbaarheidsproblemenToelichting?: string | undefined;

  /** Personeelszorg en -behoud */
  personeelszorg_en_behoud?: number | undefined;

  /** personeelszorg_en_behoud_toelichting */
  personeelszorgEnBehoudToelichting?: string | undefined;

  /** Gezondheid */
  gezondheid?: number | undefined;

  /** gezondheid_toelichting */
  gezondheidToelichting?: string | undefined;

  /** Imago / mvo */
  imago?: number | undefined;

  /** imago_toelichting */
  imagoToelichting?: string | undefined;

  /** Milieuverordening/extern verzoek */
  milieuverordening?: number | undefined;

  /** milieuverordening_toelichting */
  milieuverordeningToelichting?: string | undefined;
}

export interface IMobilityService extends Entry<IMobilityServiceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "mobilityService";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IQuestionFields {
  /** Title */
  title?: string | undefined;

  /** QuestionText */
  questionText?: string | undefined;

  /** shortQuestion */
  shortQuestion?: string | undefined;

  /** Order */
  order?: number | undefined;

  /** questionType */
  questionType?: "boolean" | "number" | undefined;

  /** minValue */
  minValue?: number | undefined;

  /** maxValue */
  maxValue?: number | undefined;

  /** identifier */
  identifier: string;
}

/** Vul hier de vragen in die gesteld moeten worden */

export interface IQuestion extends Entry<IQuestionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "question";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IWebsiteCollectiefVervoerFields {
  /** inleiding */
  inleiding?: string | undefined;

  /** Wat is collectief vervoer */
  watIsCollectiefVervoer?: string | undefined;

  /** processchema */
  processchema?: Asset | undefined;

  /** Aanleidingen voor collectieve vervoersoplossingen  */
  aanleidingenVoorCollectieveVervoersoplossingen?: string | undefined;

  /** Overzicht collectieve vervoersoplossingen */
  overzichtCollectieveVervoersoplossingen?: string | undefined;

  /** Bestuurlijke rechtsvormen */
  bestuurlijkeRechtsvormen?: string | undefined;

  /** Cover Subsidie */
  coverSubsidie?: string | undefined;

  /** Best-practices */
  bestPractices?: string | undefined;
}

export interface IWebsiteCollectiefVervoer
  extends Entry<IWebsiteCollectiefVervoerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "websiteCollectiefVervoer";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "businessParkReason"
  | "governanceModel"
  | "implementationvariations"
  | "mobilityService"
  | "question"
  | "websiteCollectiefVervoer";

export type IEntry =
  | IBusinessParkReason
  | IGovernanceModel
  | IImplementationvariations
  | IMobilityService
  | IQuestion
  | IWebsiteCollectiefVervoer;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
